### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by 0xNetizen** [myfreespirit/application-form#68]
Hi Eduard, it is Ben from the EthGlobal hackathon. I'm contacting you about a new opportunity. Check discord on the slingshot group or message me on twitter: @_0xBen

Hope you're doing well :)

**Comment by myfreespirit** [comment]
Thanks for reaching out Ben, found the message on discord :)

**Comment by 0xNetizen** [comment]
Nice :) Let me know. Thanks.
